### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by jeyaganeshn** [fyllepo/jira-report-time-logged-by-user#1]
Thanks for making this wonderful script. I am having some issues; I have listed it down.

- Unable to install dependencies (How to?)
  What I am currently doing is cloning the project in my Github Desktop and 'Open in Git Shell' running the command `composer install` throws an error. I am a novice so any help in this regard would be great. To overcome this I commented the below lines of code in index.php. After that I was able to see the UI
  ```
  require 'vendor/autoload.php';
  use League\Csv\Writer;
  ```
- Unable to connect to JIRA onCloud instance. Once I enter the key I am getting "Error: Request did not return any results, check login information or project key"

**Comment by fyllepo** [comment]
Hi @jeyaganeshn, sorry for the slow reply.

I'll update the docs on how to get started with composer, but you'll first want to visit https://getcomposer.org and get it installed locally, it's a package manager for PHP, so you can easily manage what libraries a project uses.

Secondly, as long as you use JIRA Cloud (formerly On Demand) you'll be able to use the API. You can configure the variables at the top of ````index.php```` eg:

````
$cfg = [
  'jira_host_address'  => 'https://your-jira-cloud-domain.atlassian.net',
  'jira_user_email'    => 'your_jira_account_email@example.com',
  'jira_user_password' => 'password',    
  'max_results' => '500'
];
````

Let me know if you have anymore questions :)

**Comment by jeyaganeshn** [comment]
Thanks for the information. I will surely look into the composer part. :)
I did add the details in the configuration. Once I fix the composer part; this issue should resolve I guess.
I can run it on my local machine as well right? Using XMPP or AMPPS.

Is there a place where I can request couple of feature?
