### ISSUE TITLE
Time spent on user story level

### ISSUE THREAD

**Issue by nielvrom** [fyllepo/jira-report-time-logged-by-user#3]
In our company we're logging time on user story level. Is it possible to receive the time spent from each user story in our project?

**Comment by fyllepo** [comment]
@nielvrom sorry for a late response, I somehow missed the notification.

I'd imagine this will be fine if your stories are setup in time and not points? (It's been a while but I think it's setup that way?)

Anyhow I recommend checking, line 64 in index.php
`foreach($data as $i => $issue)`

Do a `var_dump` on the $issue var and find the relevant arrays for your required data.

Hope that helps!
