### ISSUE TITLE
Entering Project Tag loads to "This page isn’t working"

### ISSUE THREAD

**Issue by vaxo101** [fyllepo/jira-report-time-logged-by-user#4]
Entering Project Tag loads to "This page isn’t working".
This page isn’t working
(IP) is currently unable to handle this request.
HTTP ERROR 500

**Troubleshooting Steps**
- Rebooted LAMP server
- Ensured details are entered correctly in index.php

**Comment by fyllepo** [comment]
@vaxo101 you could try checking your webserver error log for details of the 500 error.

If it's not easily determined, you could try the more updated fork by @hanscode44 here: https://github.com/hanscode44/jira-report-time-logged-by-user
